[Coliseum]

WhiteWorkspace = 'C:/Users/むずでょ/go/src/github.com/muzudho/kifuwarabe-go-coliseum/workspace-w'
BlackWorkspace = 'C:/Users/むずでょ/go/src/github.com/muzudho/kifuwarabe-go-coliseum/workspace-b'
