[White]

Connector = 'C:/Users/むずでょ/go/src/github.com/muzudho/gtp-engine-to-nngs/gtp-engine-to-nngs.exe'
Workspace = 'C:/Users/むずでょ/go/src/github.com/muzudho/kifuwarabe-go-coliseum/workspace-w'

[Black]

Connector = 'C:/Users/むずでょ/go/src/github.com/muzudho/gtp-engine-to-nngs/gtp-engine-to-nngs.exe'
Workspace = 'C:/Users/むずでょ/go/src/github.com/muzudho/kifuwarabe-go-coliseum/workspace-b'
