# (C) 黒プレイヤー（人間）を想定

# `Server` - 接続先の情報
[Server]

Host = 'localhost'

# 接続先サーバーのポート番号
# (^q^) 数値型のデータをクォーテーションで囲むとエラーもなく読取失敗するから注意☆
Port = 9696

# `User` - gtp-engine-to-nngs が利用する区画。人間プレイヤー、GTPエンジン、閲覧者など接続者側の情報など。
[User]

# * `Human` - 人間プレイヤーが接続する
# * `GTP` - GTP(碁テキスト プロトコル)を用いる思考エンジンが接続する
InterfaceType = 'GTP'

# EngineCommand - 思考エンジンを起動するコマンドの実行ファイル名の部分（OSにより書き方が異なるかも）
# EngineCommand = 'C:/Users/むずでょ/go/src/github.com/muzudho/gtp-engine-to-nngs/gtp-engine-to-nngs.exe' ダメ（＾～＾）無限ループする（＾～＾）
EngineCommand = 'C:/Users/むずでょ/go/src/github.com/muzudho/kifuwarabe-gtp/kifuwarabe-gtp.exe'

# EngineCommandOption - 思考エンジンを起動するコマンドの半角スペース区切りの引数（OSにより書き方が異なるかも）
EngineCommandOption = '--workdir C:/Users/むずでょ/go/src/github.com/muzudho/kifuwarabe-go-coliseum/workspace-b'

# マッチの申込
[MatchApplication]

# 自分の方から申し込むなら true, 申し込みを受けるのを待つ方なら false。
# true にしたなら、 OpponentName も設定してください
ApplyFromMe = true

# 自分の方から申し込むなら、対戦相手のアカウント名も指定してください。そうでないなら無視されます
OpponentName = "kifuwarabe"

# 白番なら 'W', 黒番なら 'B'
Phase = 'B'

# 何路盤
BoardSize = 19

# 持ち時間（分）
AvailableTimeMinutes = 40

# カナダ式秒読み。25手を何分以内に打てばよいか
CanadianTiming = 0
